version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: chat_db
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Seeds run on first boot

volumes:
  db_data: