name: Build and Push to Azure Container Registry

on:
  push:
    branches: 
      - main
      - feature_a
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set environment variables
        id: set-env
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "IMAGE_NAME=chatbot2" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/feature_a ]]; then
            echo "IMAGE_NAME=chatbot2_2" >> $GITHUB_ENV
          fi
          echo "REGISTRY=icgprodappseaacr01-etgca6a0cnbkfvd4.azurecr.io" >> $GITHUB_ENV
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ICGPRODAPPSEAACR01
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max